sudo: false  # Use container-based infrastructure
language: python
dist: trusty
python:
  - "2.7"
  - "3.6"
git:
  # don't need the default depth of 50
  # but don't want to use a depth of 1 since that affects
  # whether jobs run when you have multiple commits queued
  # https://github.com/travis-ci/travis-ci/issues/4575
  depth: 10
cache:
  pip: true
  # cache directory used for Ensembl downloads of GTF and FASTA files
  # along with the indexed db of intervals and ID mappings and pickles
  # of sequence dictionaries. Also, pip
  directories:
    - $HOME/miniconda
before_install:
  # don't install miniconda if it's already cached
  # if not yet installed, use different versions for py2 vs. py3
  - |
    if [ -d  $HOME/miniconda/bin ];
      then
      echo "miniconda already installed"
    else
      rm -rf $HOME/miniconda
      if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
      bash miniconda.sh -b -p $HOME/miniconda
    fi
  - export PATH="$HOME/miniconda/bin:$PATH"
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  # reset the shell's lookup table for program name to path mappings
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
install:
  - >
      conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
      nose pylint pandas pandoc
  - source activate test-environment
  - pip install pypandoc
  - pip install -r requirements.txt
  - pip install .
  - pip install coveralls
script:
  - ./lint.sh
  - nosetests test --verbose --with-coverage --cover-package=sercol
after_success:
  coveralls
deploy:
  provider: pypi
  user: openvax
  distributions: sdist
  password:
    secure: "uZmWXkTgFk+TG1HgOlhVcI9/4aMkbTZE2r9pO1gRjPzTb2ssK8e5oKdmSWESB9GfDpahyGW6KrTH4lSQuiJ+ePMk7tNi81pc8mMQg0AzpI/2JGXUEomhf6OorBrDL8U2lxZhBeaTtfPvvXHL45F4tCdne3hZuFIgvPcU/CCXGlNbyG8+luE9QrWxS7Vudwgl9vsFGilDmvKTM16hMHAXf1A2Q2a5J4n6Nwr7cdEC041dsFa3+KiKP9dv9LUfB2dmTrCyH9CCBCt+RIOYhRCNzi5QTXLqUH5/EWCK+GNB3kksn2nsWt5FvmGJeuhc93zevrmhw+XttW7YWZOeucwTJY7kKGzQ65wLktbqgw1/avXffQGbNrcvsSNtBMcj9tp8eVtYrZXkhLL6fukVI8ZK35m8x+XHz01YUk8T6NLsSypHwc21B4hL6s52qcjjHGrBDHoCaa3cTPeAwepnqse0qrzmpotCKHmtjk4fyTTpStz8VcUi5WFrD0iP+dS4xtEMDRWwCLuYWob5VOKCUvpPu+1aMfN33zjikSyN1ooQVtmJzTgm3hFgzygbFDCBCvBydcfpgGj39TctkgJUFE5/wzfXhbokb0p04+IoDY79zPxyHWKBLZaaZZOB3vdv5a+fzAZR6boT3ENBkiuVbQ5gfSgN2B5wNTqiZ19Ouzu6cKY="
  on:
    branch: master
    condition: $TRAVIS_PYTHON_VERSION = "2.7"